# Generated by Django 4.2.7 on 2023-11-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0002_remove_receiver_category_receivercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
