# Generated by Django 4.2.7 on 2023-11-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0004_alter_sender_email_backend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='EMAIL_USE_TLS',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
